### ISSUE TITLE
Incompatible with Spectrum

### ISSUE THREAD

**Issue by ItsYaBoyYeeter** [Terrails/HealthOverlay#44]
https://paste.ee/p/XRVMn
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Spectrum' (spectrum) 1.6.3-1.19.2-leisure_time with any version that is compatible with:
		 - healthoverlay 7.1.1
Unmet dependency listing:
	 - Mod 'Spectrum' (spectrum) 1.6.3-1.19.2-leisure_time is incompatible with any version of mod 'Health Overlay' (healthoverlay), but a matching version is present: 7.1.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Terrails** [comment]
Spectrum is blocking Health Overlay using their mod config file. I'm guessing it is some incompatibility. I might look into what might be causing the issue, but do not count on it.
